### PR TITLE
Contributor Abha Rana, Himanshu Sharma---> This is our final commit f…

### PR DESCRIPTION
**Pull request by senseihimanshu**
…or this project, lets Insta, Abha please join Insta

### CODE REVIEW

**Comment by vishivish18** [comment]
@senseihimanshu I hope you can write better commit/PR messages.  And I assume this is your last commit so your code is bug free. I will review the code and project tonight

**Comment by senseihimanshu** [comment]
@vishivish18 Yes Vishal, We added this commit message for fun! 
We will create good commit messages in future.

**Comment by vishivish18** [comment]
@senseihimanshu  Chill, I too commented for fun. 😄 We can have fun , as long as we don't harm the work.

**Comment by senseihimanshu** [comment]
Yes Vishal! Thanks...

**Review by KritikaSachdeva — APPROVED** [review]

**Pull request merged**
